apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cat-repo
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/oksuriini/CatRegistry
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: cat-registry
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./tf
  sourceRef:
    kind: GitRepository
    name: cat-repo
    namespace: flux-system
  tfVarsFiles: ["example.tfvars"]
