kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: flux-system
  name: pod-creator
rules:
  - apiGroups: ["", apps]
    resources: [pods, deployments, services, statefulsets]
    verbs: [create, get, list, delete, update, patch]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-creator-def
rules:
  - apiGroups: ["", apps]
    resources: [pods, deployments, services, statefulsets]
    verbs: [create, get, list, delete, update, patch]
